---
- name: Ensure unzip is installed
  apt:
    name: unzip
    state: present
  become: yes

- name: Download AWS CLI v2 installer
  get_url:
    url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /tmp/awscliv2.zip

- name: Unpack AWS CLI
  unarchive:
    src: /tmp/awscliv2.zip
    dest: /tmp/
    remote_src: yes

- name: Install AWS CLI
  command: /tmp/aws/install
  args:
    creates: /usr/local/bin/aws
