apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-receiver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-receiver
  template:
    metadata:
      labels:
        app: alert-receiver
    spec:
      containers:
        - name: alert-receiver
          image: alert-receiver:latest
          ports:
            - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: alert-receiver-service
spec:
  selector:
    app: alert-receiver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
