# tags: awscli, setup, automation

---
- name: Install and configure AWS CLI
  hosts: localhost
  become: yes
  roles:
    - role: awscli
      vars:
        aws_access_key: "your-access-key"
        aws_secret_key: "your-secret-key"
        aws_region: "us-east-1"
