name: Python CI
on:
  push:
    paths:
      - "lambda_src/**"
      - "tests/**"
      - "requirements-dev.txt"
      - ".flake8"
      - "pytest.ini"
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: requirements-dev.txt
      - run: pip install -r requirements-dev.txt
      - name: Lint (flake8)
        run: flake8 lambda_src tests
      - name: Black (check-only)
        run: |
          pip install black
          black --check --exclude "(requests|urllib3|idna|charset_normalizer|certifi|bin)" lambda_src tests
      - name: Run tests (pytest + coverage)
        run: |
          pip install coverage
          pytest -q --maxfail=1 --disable-warnings --cov=lambda_src --cov-report=xml
      - name: Upload coverage to artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
